### ISSUE TITLE
Image broken (Does not boot to display manager)

### ISSUE THREAD

**Issue by ryanabx** [Drakulix/infinity#1]
Hello,
I know that this image has not been updated in a while, but I decided to try using it anyways!

The image boots, but there's seemingly no display manager that pops up. I had to ctrl+alt+f2 to get to a terminal and then run `cosmic-session` manually to get into COSMIC and even still some things were missing:

* cosmic-settings wasn't available
* cosmic-store wasn't available
* cosmic-term wasn't available
* I couldn't use the meta/super key to pop up the cosmic launcher either.
* Seemingly no wallpaper functionality

Until a display manager is implemented for cosmic, perhaps using GDM would be nice.

My device is an ASUS GA402RJ with an AMD Ryzen 9 6900hs and a Radeon 6700S dGPU

Great work on COSMIC/Smithay by the way!

**Comment by ryanabx** [comment]
I'm working on trying to get an updated build on my own fork: https://github.com/ryanabx/infinity

Currently the CI is having issues because github runners went down in total storage since this was made, and it runs out of storage when downloading the fedora image...

**Comment by ryanabx** [comment]
Related: https://github.com/pop-os/cosmic-greeter/issues/8

I fixed this in my fork by using SDDM for the time being. Not ideal but it provides a 'working' experience for now

**Comment by ryanabx** [comment]
The remaining stuff is because the image wasn't up-to-date. Closing this issue

**Comment by Drakulix** [comment]
I think the big problem with greetd is selinux support right now. I am personally still using this image and with selinux disabled it mostly works fine.

But obviously this isn't exactly a workable solution for a proper cosmic spin. Btw, feel free to ping me, should you create a SIG for this. :)

**Comment by ryanabx** [comment]
> I think the big problem with greetd is selinux support right now. I am personally still using this image and with selinux disabled it mostly works fine.

Hi, turns out the issue was that there was no cosmic-greeter user being created. I went ahead and made a PR at cosmic-greeter https://github.com/pop-os/cosmic-greeter/pull/13 that solves this on my image, it uses systemd-sysusers and systemd-tmpfiles to make a temporary system user and home directory for it.

But in addition SELinux support will be nice to have, since disabling it is, well, not secure 😁

> But obviously this isn't exactly a workable solution for a proper cosmic spin. Btw, feel free to ping me, should you create a SIG for this. :)

I will keep you posted! I plan on making a matrix chat soon. Hopefully the SIG takes off :)

**Comment by ryanabx** [comment]
@Drakulix the matrix server has been created! https://matrix.to/#/#fedora-cosmic:fedora.im

The Fedora Rust SIG wants to work with the COSMIC SIG as they are the ones who package a lot of Rust packages for Fedora
